/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 the_universe.glb
Author: Stark (https://sketchfab.com/stark3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-universe-ef1aa837c6fb480b8691c212a4d63d9d
Title: The Universe!
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/the_universe.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="4a9d9c70ef3344299ddbb524fe702fc7fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="pPipe2">
                  <group name="polySurface1" scale={3}>
                    <mesh
                      name="polySurface1_Mat_Aro_0"
                      geometry={nodes.polySurface1_Mat_Aro_0.geometry}
                      material={materials.Mat_Aro}
                    />
                  </group>
                  <group name="polySurface2" rotation={[0, -1.549, 0]}>
                    <mesh
                      name="polySurface2_Mat_Esfera_0"
                      geometry={nodes.polySurface2_Mat_Esfera_0.geometry}
                      material={materials.Mat_Esfera}
                    />
                  </group>
                  <group
                    name="polySurface3"
                    rotation={[-Math.PI / 2, 1.507, -Math.PI]}
                  >
                    <mesh
                      name="polySurface3_Mat_Esfera_0"
                      geometry={nodes.polySurface3_Mat_Esfera_0.geometry}
                      material={materials.Mat_Esfera}
                    />
                  </group>
                  <group
                    name="polySurface4"
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={2}
                  >
                    <mesh
                      name="polySurface4_Mat_Aro_0"
                      geometry={nodes.polySurface4_Mat_Aro_0.geometry}
                      material={materials.Mat_Aro}
                    />
                  </group>
                  <group
                    name="polySurface5"
                    rotation={[-2.356, -1.539, -Math.PI]}
                  >
                    <mesh
                      name="polySurface5_Mat_Esfera_0"
                      geometry={nodes.polySurface5_Mat_Esfera_0.geometry}
                      material={materials.Mat_Esfera}
                    />
                  </group>
                  <group
                    name="polySurface6"
                    rotation={[Math.PI / 4, 0, 0]}
                    scale={4}
                  >
                    <mesh
                      name="polySurface6_Mat_Aro_0"
                      geometry={nodes.polySurface6_Mat_Aro_0.geometry}
                      material={materials.Mat_Aro}
                    />
                  </group>
                  <group
                    name="polySurface7"
                    rotation={[-Math.PI / 4, 1.547, 0]}
                  >
                    <mesh
                      name="polySurface7_Mat_Esfera_0"
                      geometry={nodes.polySurface7_Mat_Esfera_0.geometry}
                      material={materials.Mat_Esfera}
                    />
                  </group>
                  <group name="polySurface8" rotation={[-Math.PI / 4, 0, 0]}>
                    <mesh
                      name="polySurface8_Mat_Aro_0"
                      geometry={nodes.polySurface8_Mat_Aro_0.geometry}
                      material={materials.Mat_Aro}
                    />
                  </group>
                </group>
                <group name="pSphere2" position={[0.034, 0, 0.083]}>
                  <mesh
                    name="pSphere2_Mat_Nucleo_0"
                    geometry={nodes.pSphere2_Mat_Nucleo_0.geometry}
                    material={materials.Mat_Nucleo}
                  />
                </group>
                <group name="pSphere5">
                  <mesh
                    name="pSphere5_Mat_Esferas2_0"
                    geometry={nodes.pSphere5_Mat_Esferas2_0.geometry}
                    material={materials.Mat_Esferas2}
                  />
                </group>
                <group name="pSphere6" scale={1.053}>
                  <mesh
                    name="pSphere6_Mat_Orb2_0"
                    geometry={nodes.pSphere6_Mat_Orb2_0.geometry}
                    // material={materials.Mat_Orb2}
                  />
                  <meshPhysicalMaterial transparent opacity={0.5} />
                </group>
                <group name="pSphere7">
                  <mesh
                    name="pSphere7_Mat_Orb_0"
                    geometry={nodes.pSphere7_Mat_Orb_0.geometry}
                    // material={materials.Mat_Orb}
                  />
                  <meshStandardMaterial opacity={0.5} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/the_universe.glb");
